### ISSUE TITLE
Luna potion causing error

### ISSUE THREAD

**Issue by fr0573** [stg-trainer-annon/BT-Silver-Base#70] opened 2016-12-30 07:03 UTC
when i give Hermione the Luna potion, game crashes

this is the error:
[code]
I'm sorry, but an uncaught exception occurred.

While loading <'Image' '01_hp/13_characters/luna/base/cheeks_01.png'>:
  File "game/script.rpy", line 14, in script call
    call select_start
  ...
  File "game/00_hp_rpy/01_hp_main_night.rpy", line 124, in script call
    call c_r_night
  File "game/00_hp_rpy/39_mo_potions.rpy", line 1234, in script
    her "Ughhh... I feel like I'm going to throw up! Did the Polyjuice work??"
IOError: Couldn't find file '01_hp/13_characters/luna/base/cheeks_01.png'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script call
    call select_start
   ...
  File "game/00_hp_rpy/01_hp_main_night.rpy", line 124, in script call
    call c_r_night
  File "game/00_hp_rpy/39_mo_potions.rpy", line 1234, in script
    her "Ughhh... I feel like I'm going to throw up! Did the Polyjuice work??"
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\ast.py", line 603, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\exports.py", line 1135, in say
    who(what, interact=interact)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\character.py", line 873, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\character.py", line 719, in do_display
    **display_args)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\character.py", line 510, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\ui.py", line 278, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\display\core.py", line 2496, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\display\core.py", line 2850, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\display\core.py", line 1916, in draw_screen
    renpy.config.screen_height,
  File "renpy/display/render.pyx", line 416, in renpy.display.render.render_screen (gen\renpy.display.render.c:6685)
    rv = render(root, width, height, 0, 0)
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen\renpy.display.render.c:2857)
    rv = d.render(widtho, heighto, st, at)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\display\layout.py", line 661, in render
    surf = render(child, width, height, cst, cat)
  File "renpy/display/render.pyx", line 103, in renpy.display.render.render (gen\renpy.display.render.c:3319)
    cpdef render(d, object widtho, object heighto, double st, double at):
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen\renpy.display.render.c:2857)
    rv = d.render(widtho, heighto, st, at)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\display\layout.py", line 661, in render
    surf = render(child, width, height, cst, cat)
  File "renpy/display/render.pyx", line 103, in renpy.display.render.render (gen\renpy.display.render.c:3319)
    cpdef render(d, object widtho, object heighto, double st, double at):
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen\renpy.display.render.c:2857)
    rv = d.render(widtho, heighto, st, at)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\display\layout.py", line 661, in render
    surf = render(child, width, height, cst, cat)
  File "renpy/display/render.pyx", line 103, in renpy.display.render.render (gen\renpy.display.render.c:3319)
    cpdef render(d, object widtho, object heighto, double st, double at):
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen\renpy.display.render.c:2857)
    rv = d.render(widtho, heighto, st, at)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\display\screen.py", line 618, in render
    child = renpy.display.render.render(self.child, w, h, st, at)
  File "renpy/display/render.pyx", line 103, in renpy.display.render.render (gen\renpy.display.render.c:3319)
    cpdef render(d, object widtho, object heighto, double st, double at):
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen\renpy.display.render.c:2857)
    rv = d.render(widtho, heighto, st, at)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\display\layout.py", line 661, in render
    surf = render(child, width, height, cst, cat)
  File "renpy/display/render.pyx", line 103, in renpy.display.render.render (gen\renpy.display.render.c:3319)
    cpdef render(d, object widtho, object heighto, double st, double at):
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen\renpy.display.render.c:2857)
    rv = d.render(widtho, heighto, st, at)
  File "renpy/display/accelerator.pyx", line 108, in renpy.display.accelerator.transform_render (gen\renpy.display.accelerator.c:2027)
    cr = render(child, widtho, heighto, st - self.child_st_base, at)
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen\renpy.display.render.c:2857)
    rv = d.render(widtho, heighto, st, at)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\display\im.py", line 478, in render
    im = cache.get(self)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\display\im.py", line 200, in get
    surf = image.load()
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\display\im.py", line 529, in load
    surf = renpy.display.pgrender.load_image(renpy.loader.load(self.filename), self.filename)
  File "D:\Downloads\WT Silver\WT Silver\WT Silver 1.12 WIN\WT_Silver_1.12-win\renpy\loader.py", line 536, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file '01_hp/13_characters/luna/base/cheeks_01.png'.

Windows-8-6.2.9200
Ren'Py 6.99.11.1749
WT Silver 1.12
[/code]

**Comment by rtozm** [comment] 2017-01-17 00:25
I was bored so I looked into this. The problem is, that the paths for the images of Luna are messed up. 
You can work around it by going to /game/01_hp/13_characters/luna
There you add a new folder named "base". In this folder you place the file cheeks_1.png which you find in body/face/cheeks 
You have to rename this file to cheeks_01.png
After that the event should run without a major error. Unfortunately there will still be an error that her boobs don't show. While this doesn't cause an error screen it's taking the fun out of this screen.

**Comment by stg-annon** [comment] 2017-01-18 21:42
so part of the problem is that there is some effort being made to rewrite a lot of code to be more Object based and there has been some overlap in the two branches causing the paths to change for luna, I'll look into reverting the changes made to the main branch.

**Comment by fr0573** [comment] 2017-01-21 06:19
thanks guys, looking forward to the fix ^^

**Comment by stg-annon** [comment] 2017-01-22 04:30
this problem was fixed as of f0a8d85d9a2fd521a6953a4dfd4d992688c24de2

**Closed as completed by stg-annon** 2017-01-22 04:30 UTC
